### ISSUE TITLE
Crash when dismissing controller containing bannerAd

### ISSUE THREAD

**Issue by sahibhussain** [mopub/mopub-ios-sdk#353] opened 2020-11-16 17:25 UTC
app crashes when i dismiss the viewcontroller when bannerAd is showing!

[crash.pdf](https://github.com/mopub/mopub-ios-sdk/files/5548613/crash.pdf)

<img width="1440" alt="Screenshot 2020-11-16 at 10 53 46 PM" src="https://user-images.githubusercontent.com/20224571/99286280-a5e1af00-285e-11eb-82e0-80d9204a1096.png">

#### MoPub SDK Version:
5.14.1

#### Device model and OS Version:
iPhone SE (1st generation) - but happening on all devices
OS: 14.2

#### Xcode Version:
12.2

**Comment by sahibhussain** [comment] 2020-11-16 17:56
i had to remove view from superview on closeButtonClick method to remove the crash

**Comment by p158276** [comment] 2020-11-17 09:36
Hi @sahibhussain ,
Thanks for reaching out. 
Do you mean the app crashes when you try to dismiss the ad and banner ad attach on the screen at the same time?
I am not able to reduce this problem in our sample app. Can you share your ad unit id and reproduce steps with us?

Yoyo Lin
MoPub Team

**Comment by sahibhussain** [comment] 2020-11-17 15:47
there is a banner ad in my viewcontroller and when i dismiss my viewcontroller while the ad is showing it crashes

**Comment by p158276** [comment] 2020-11-18 09:45
Hi @sahibhussain , 
Thanks for sharing. Regarding to the ad unit id, are you using the id [here](https://developers.mopub.com/publishers/ios/test/#option-2-test-using-mopub-test-ad-units)?
If yes, which id are you using now?
As we cannot reproduce the scenario on our end, can you provide the reproducible code snippet or project with us? 

Thanks.

**Comment by sahibhussain** [comment] 2020-11-18 14:49
Hi @p158276 
i cant share the code as it is in our live project and i'll have to create a demo project just for this

also i need to know that 
when i am using native ad with sample ad_unit_id i get the ad just fine but when i am using real ad_unit_id i get
`Ad server returned no inventory`

and while using banner ad again in sample ad_unit_id i get the ad but when i use real ad_unit_id i get
`The operation couldn’t be completed. (com.mopub.iossdk error 0.)`

**Comment by sahibhussain** [comment] 2020-11-18 14:49
i getting rewarded ad perfectly in both sample and real ad_unit_id

**Comment by sahibhussain** [comment] 2020-11-18 14:51
> Hi @sahibhussain ,
> Thanks for sharing. Regarding to the ad unit id, are you using the id [here](https://developers.mopub.com/publishers/ios/test/#option-2-test-using-mopub-test-ad-units)?
> If yes, which id are you using now?
> As we cannot reproduce the scenario on our end, can you provide the reproducible code snippet or project with us?
> 
> Thanks.


Banner (MRect) | 300x250 | 2aae44d2ab91424d9850870af33e5af7
-- | -- | --

**Comment by p158276** [comment] 2020-11-20 10:39
Hi @sahibhussain ,
We are still not able to reproduce the crash from our end.
Would you able to share the code snippet or demo project to address this issue?

**Comment by chauduyphanvu** [comment] 2020-12-04 22:34
No repro. Closing.

**Closed by chauduyphanvu** 2020-12-04 22:34 UTC
