### ISSUE TITLE
MoPub SDK 5.5.0 hung

### ISSUE THREAD

**Issue by KAMIKAZEUA** [mopub/mopub-ios-sdk#255] opened 2019-02-01 14:45 UTC
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.5.0
#### Device model and OS Version:
iOS 12.1.2, iPhone 6
#### Xcode Version:
10.1
#### Ad Unit IDs used in reproducing the issue:
No matter.
#### Steps to reproduce the behavior:
Init MoPub SDK

#### Expected behavior:
After init should not hang.

#### Observed behavior:
Game hung.

#### Evidence:

My game in on a production, works very stable and uses previous MoPub SDK 5.4.1

Today I updated to 5.5.0
https://github.com/mopub/mopub-ios-sdk/releases/tag/5.5.0

Replaced .framework as long as new adapters files from the official repo and all adapters SDK all latest for my game.

And when I started my game and it immediately hung(after initialization of MoPub).

What I noticed first previous .framework file size for iOS build was 4.1Mb now, when I used framework from iphoneos folder it's around 18Mb.

Don't know if I should create another bug. I tried to upgrade because in new version I have that iphoneos file.

So, I revered to 5.4.1 and since now I will very very carefully update MoPub SDK 😨

There are no any unusual traces at that point.
Game just starts as it should, then after call init of MoPub it's dropped CPU usage to 0% and hung. So weird, Xcode just showing 0% of usage.

Sometimes, it works I'd say 1 try from 10.

If I'm not calling init of MoPub, game works as it should. My game build with cocos2d-x and it uses OpenGL.

**Comment by sdolim** [comment] 2019-02-01 18:16
Something that came up recently in Unity builds was having two copies of the MoPub SDK in the Xcode project, one from the .framework, and one from the pod dependencies specified by the adapter podspecs.  Can you check that you don't have two SDK?  If you do that could lead to this weird behavior.

**Comment by chauduyphanvu1** [comment] 2019-02-01 20:40
> p.s. what is so dramatic changes were done as framework size rises from 4mb to 18mb?

@kdun 

> And when I started my game and it immediately hung(after initialization of MoPub).

The only change going from 5.4.1 to 5.5.0 regarding initialization is that, the MoPub SDK also asynchronously initializes supported networks whose adapters are found in the app project. Here's a couple of things you could try:

* Use Xcode's Instruments to profile the game at the time it is about to freeze. Feel free to send us your traces for investigation. 
* Remove some (or all) adapters from your game and let us know if the app freeze persists. 
* Check the fps reading of the game. How much does it drop?
* Do you build your game for Android? If so, do you see this lag there?

**Comment by KAMIKAZEUA** [comment] 2019-02-01 21:09
1. Game is under NDA, I can't send any, sorry. I wish to.
2. I'm on about to release update for my game, so perhaps in 1 week I can back to this.
3. It was 0, I checked and CPU load was 0.
4. No, never.

**Comment by kdun** [comment] 2019-02-04 17:37
@KAMIKAZEUA The increase in framework binary size is due to inclusion of bitcode (we now set `BITCODE_GENERATION_MODE = bitcode` when generating the frameworks).

Can you tell us more about where and how the MoPub SDK is initialized?
- Is it being called in `application:didFinishLaunchingWithOptions:`? 
- Current thread, main thread or GCD async thread? 
- Are you waiting for the MoPub SDK initialization completion block or not using it?

**Comment by KAMIKAZEUA** [comment] 2019-02-04 17:42
@kdun 

- Init called after game scene fully loaded + 2 seconds. I'm not doing anything in `didFinishLaunchingWithOptions`. 
- Main thread.
- Waiting for completion and then start initing and loading banners, loadInterstitials and rewarded videos. 

Feel free to ask anything more if needed.

**Comment by chauduyphanvu1** [comment] 2019-03-22 17:41
@KAMIKAZEUA - do you still run into this issue? Did you have a chance to try our previous recommendations? We're closing this thread and feel free to reopen if needed!

**Comment by rsatrasala** [comment] 2019-03-22 17:41
Closing this issue due to inaction.

**Closed by rsatrasala** 2019-03-22 17:41 UTC

**Comment by KAMIKAZEUA** [comment] 2019-03-22 17:45
Very fun, you just asked and then closed issue).

I haven’t tried because I’m not using latest SDK, just stick with older version.

I have no time for that now. But issue is there for sure.

**Comment by KAMIKAZEUA** [comment] 2019-03-22 17:46
Just try to integrate this with cocos2d-x and you will get this issue..

**Comment by chauduyphanvu1** [comment] 2019-03-22 18:08
@KAMIKAZEUA - we don't support Cocos2d-x so we are unable to reproduce the issue using the details you provided. Feel free to open another issue report if you get a chance to share a debug project in the future!
