### ISSUE TITLE
Crash when debug in Allocations 

### ISSUE THREAD

**Issue by chenxi141017** [mopub/mopub-ios-sdk#397] opened 2021-07-29 09:09 UTC
I use `Allocations` to track my game's heap usage,  after 
[allocations-crash-log.txt](https://github.com/mopub/mopub-ios-sdk/files/6899311/allocations-crash-log.txt)
click the `start` button , it crash until invoke the `rewardedAdDidLoadForAdManager:` method.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.16.2

#### Device model and OS Version:
iPhone XR  iOS 14.2

#### Xcode Version:
12.2

#### Ad Unit IDs used in reproducing the issue:
5323ff63e9b04829abf26482cda6d3fe

#### Steps to reproduce the behavior:
- Launch `Instruments` , Select `Allocations`
- Select my game
- Click `start` button

#### Expected behavior:
No crash.

#### Observed behavior:
- Run my game from Xcode is ok!
- Integrate MoPub SDK to Unity, Unity version is 2018.4.14f1

#### Evidence:
<img width="841" alt="截屏2021-07-29 下午4 59 32" src="https://user-images.githubusercontent.com/14297268/127463535-1cd6909f-77f2-48cc-90b7-55674b9ad1b8.png">

[console log file](https://github.com/mopub/mopub-ios-sdk/files/6899315/allocations-crash-log.txt)

**Comment by chauduyphanvu** [comment] 2021-08-02 15:52
@chenxi141017, thank you for the report. Could you please either share your project where you reproduce the crash or attempt to replicate it in our [sample app](https://github.com/mopub/mopub-unity-sdk/tree/master/unity-sample-app)? If the crash occurs in the sample app, could you share with us the steps/code that you use?

Since you mention this is seen on Unity iOS builds, I'd recommend moving this issue to the [Unity GitHub tracker](https://github.com/mopub/mopub-unity-sdk/issues). 

Vu Chau
MoPub Team

**Comment by chenxi141017** [comment] 2021-08-06 07:20
fix this issue by update Xcode to 12.5.1

**Closed** 2021-08-06 07:20 UTC
