### ISSUE TITLE
Crash in MPRateLimitManager.m still happening

### ISSUE THREAD

**Issue by polmum** [mopub/mopub-ios-sdk#276] opened 2019-06-26 13:59 UTC
This looks like the same crash reported in #269. We've updated to MoPub 5.7.1 as recommended but the crash is still happening.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.7.1

#### Device model and OS Version:
iPhone (5s, 6, 6s, 6 Plus, 7, 8, X, etc), iPad (Mini, Mini 2, Mini 4, Pro, etc)
iOS 10 - iOS 12

#### Xcode Version:
Xcode 10.2.1

#### Steps to reproduce the behavior:
As mentioned in the original issue, we can't reproduce this crash, but it's top 5 on our Fabric dashboard.

#### Evidence:
[crash.txt](https://github.com/mopub/mopub-ios-sdk/files/3330346/crash.txt)

**Comment by chauduyphanvu** [comment] 2019-06-26 14:37
@polmum, thanks for letting us know. I'll relay the info to the rest of the team and we'll see what can be done to fix the crash.

Vu Chau
MoPub SDK Team

**Comment by stevenp** [comment] 2019-07-06 16:53
10 days have passed now since your last comment. This continues to happen and is the top cause of crashes in my app at the moment. Is this being treated as a P0 level issue? I'm going to need to disable MoPub in my app until you're able to correct this. It's especially frustrating because in https://github.com/mopub/mopub-ios-sdk/issues/269 you claimed that this was resolved.

**Comment by chauduyphanvu** [comment] 2019-07-08 15:20
@stevenp, I've bumped the priority of this issue internally for the rest of the team. We'll share more updates as soon as we have them.

**Comment by chauduyphanvu** [comment] 2019-07-08 20:01
@stevenp, we've cut the release for our 5.8.0 SDK so this won't get into that version, but the team has some ideas of fixing this crash and we'll try to get it in the SDK version after that.

Meanwhile, I know this crash is not reproducible but do you have any other info on how you are integrating/implementing the MoPub SDK? Specifically I'm looking for info on what the app is doing prior to the time of the crash.

**Comment by stevenp** [comment] 2019-07-08 23:30
Thanks, @chauduyphanvu. I'm not doing anything special, but from what I can tell in the crash, it appears as though somehow the ad unit ID passed to `MPRateLimitManager.setRateLimitTimerWithAdUnitId` is nil. 

The stack trace isn't super clear about what's happening on my end, other than that it begins inside the task block in `MPAdServerCommunicator.loadURL`. I've hacked it to try to catch the runtime exception and treat it as a failure, but I haven't been able to reproduce it.

**Comment by chauduyphanvu** [comment] 2019-07-10 18:24
@stevenp, we'll push out a fix in 5.8.0 to check for a nil ad unit ID, and fast fail. While it does not effectively fix the root cause of the crash, it should prevent crashes like this downstream.

**Comment by rsatrasala** [comment] 2019-07-23 22:56
5.8.0 is released. Closing this issue.

**Closed by rsatrasala** 2019-07-23 22:56 UTC
