### ISSUE TITLE
MoPub SDK Crash while mp_endUpdates

### ISSUE THREAD

**Issue by SSamanta** [mopub/mopub-ios-sdk#268] opened 2019-05-09 03:14 UTC
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
This is a random crash.

#### Expected behavior:
The application should not crash

#### Observed behavior:
This crash is happening for long months.

#### Evidence:
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
    frame #0: 0x000000018b2e7cc4 libobjc.A.dylib`objc_exception_throw
    frame #1: 0x000000018bff5434 CoreFoundation`+[NSException raise:format:arguments:] + 108
    frame #2: 0x000000018cacf754 Foundation`-[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 116
    frame #3: 0x00000001b91b18ac UIKitCore`-[UITableView _endCellAnimationsWithContext:] + 14516
    frame #4: 0x00000001b91c8364 UIKitCore`-[UITableView endUpdates] + 92
  * frame #5: 0x0000000105af5124 MoPub`-[UITableView(self=0x000000010783f800, _cmd="mp_endUpdates") mp_endUpdates] at MPTableViewAdPlacer.m:686:5
    frame #6: 0x0000000105af0000 MoPub`-[MPTableViewAdPlacer adPlacer:didLoadAdAtIndexPath:](self=0x0000000281414080, _cmd="adPlacer:didLoadAdAtIndexPath:", adPlacer=0x00000002827d8b60, indexPath=0x807885aa16d13388) at MPTableViewAdPlacer.m:114:5
    frame #7: 0x0000000105aee11c MoPub`-[MPStreamAdPlacer fillAdsInConsideredRange](self=0x00000002827d8b60, _cmd="fillAdsInConsideredRange") at MPStreamAdPlacer.m:515:9
    frame #8: 0x0000000105ae99e0 MoPub`-[MPStreamAdPlacer setVisibleIndexPaths:](self=0x00000002827d8b60, _cmd="setVisibleIndexPaths:", visibleIndexPaths=@"5 elements") at MPStreamAdPlacer.m:93:5
    frame #9: 0x0000000105aefd30 MoPub`-[MPTableViewAdPlacer updateVisibleCells](self=0x0000000281414080, _cmd="updateVisibleCells") at MPTableViewAdPlacer.m:99:9
    frame #10: 0x000000018b2e3454 libobjc.A.dylib`-[NSObject performSelector:withObject:] + 68
    frame #11: 0x0000000105af6d64 MoPub`-[MPTimer timerDidFire](self=0x0000000281451980, _cmd="timerDidFire") at MPTimer.m:61:5
    frame #12: 0x000000018cb7f2f4 Foundation`__NSFireTimer + 88
    frame #13: 0x000000018c06ffb8 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
    frame #14: 0x000000018c06fce4 CoreFoundation`__CFRunLoopDoTimer + 900
    frame #15: 0x000000018c06f4c8 CoreFoundation`__CFRunLoopDoTimers + 252
    frame #16: 0x000000018c06a198 CoreFoundation`__CFRunLoopRun + 1812
    frame #17: 0x000000018c069764 CoreFoundation`CFRunLoopRunSpecific + 452
    frame #18: 0x000000018e2a5dd4 GraphicsServices`GSEventRunModal + 108
    frame #19: 0x00000001b8fc000c UIKitCore`UIApplicationMain + 216
    frame #20: 0x0000000104e39384 XXXX`main(argc=1, argv=0x000000016b0677b0) at main.m:18:16
    frame #21: 0x000000018bb28ffc libdyld.dylib`start + 4
(lldb)

**Comment by chauduyphanvu1** [comment] 2019-05-10 15:58
@SSamanta - thanks for letting us know! Could you describe to us what's happening in the app at the time of the crash (this looks like there's an update to the UITableView from your app at the same time MoPub updates it for the ad cells)? If you are able to reproduce the crash, could you send us a link to download a mini app project?

Vu Chau
MoPub SDK Team

**Comment by rsatrasala** [comment] 2019-06-21 20:39
Closing. Please open a new issue if needed.

**Closed by rsatrasala** 2019-06-21 20:39 UTC
