### ISSUE TITLE
Crashes on 103 MPLogManager.m

### ISSUE THREAD

**Issue by djaygit** [mopub/mopub-ios-sdk#286] opened 2019-09-13 13:28 UTC
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior: just added the banner in home and it crashed
Please list all relevant steps to reproduce the observed behavior. objC ios app. add banner on home page

#### Expected behavior: no crash
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
<img width="1505" alt="Screenshot 2019-09-13 at 6 56 07 PM" src="https://user-images.githubusercontent.com/1255841/64865979-2fdd2900-d658-11e9-8cca-d1a79a8707a4.png">

also crashed Crashes on 103 MPLogManager.m
in simulator

Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment] 2019-09-13 13:34
@djaygit, 4.16.0 is a very old release and we've improved logging (new features for + bug fixes) in the 5.5.0 SDK. Do you think you could upgrade to one of the newer SDK versions to get the new features and bug fixes?

Vu Chau
MoPub SDK Team

**Comment by djaygit** [comment] 2019-09-13 21:07
I'm using "https://bit.ly/2bH8ObO" which i found on https://developers.mopub.com/publishers/ios/get-started/#option-1-zipped-source

**Comment by chauduyphanvu** [comment] 2019-09-16 14:50
@djaygit, I see. I was misled by the 4.16.0 SDK version that you put in the issue description. 

In this case, since you are already using the 5.5.0 SDK version, could you send me a zip of your Xcode project with which you saw the crash so we can debug the issue? Alternatively, you can paste here the code you use to initialize the MoPub SDK. If either option isn't possible, check out how our [iOS sample app does initialization](https://github.com/mopub/mopub-ios-sdk/blob/42bd0a4a365bacbbc9c4fe56fcec16c57629fd74/Canary/Canary/AppDelegate%2BInitialization.swift#L52-L70) and you could cross-check to see where the difference is that might result in a crash.

**Comment by djaygit** [comment] 2019-09-17 08:01
@chauduyphanvu send you the project link on twitter, you can reply there. thanks for your help

**Comment by djaygit** [comment] 2019-09-20 21:35
@chauduyphanvu please update on this 
thanks

**Comment by chauduyphanvu** [comment] 2019-09-23 14:58
@djaygit, thanks for sending over the test app! I can confirm I was able to reproduce the exact crash, however it only happened once during the test session, so I did not have a chance to debug the issue.

Do you have a chance to upgrade to the latest 5.9.0 SDK release for this app? That is because we've had [a number of different changes](https://github.com/mopub/mopub-ios-sdk/commits/853cbf22ef14c3f5e4aedcf6f00c944d3a2b9843/MoPubSDK/Internal/MPMediationManager.m) to the class (MPMediationManager.m) where the crash occurs, so this issue might have been addressed in one of the releases. If you still see the issue in 5.9.0, we can certainly assist with debugging it.

**Comment by djaygit** [comment] 2019-09-24 19:22
same issue Crashed on 103 MPLogManager.m using 5.9.0

**Comment by chauduyphanvu** [comment] 2019-09-25 20:13
@djaygit, thank you for the confirmation! Could you please send the updated project over (like how you sent the first one)?

**Comment by djaygit** [comment] 2019-09-25 20:18
@chauduyphanvu  sent you the update version link

**Comment by chauduyphanvu** [comment] 2019-09-26 14:01
@djaygit So I'm not seeing the MoPub SDK is getting initialized in your app. That might be potentially leading to the crash. Could you initialize MoPub before making your ad requests?

```obj-c
MPMoPubConfiguration *sdkConfig = [[MPMoPubConfiguration alloc] initWithAdUnitIdForAppInitialization:@"AD_UNIT_ID"];

[[MoPub sharedInstance] initializeSdkWithConfiguration:sdkConfig completion:^{
        NSLog(@"SDK initialization complete");

        // SDK initialization complete. Make your ad requests here.
}];
```

Try that and let me know if you still see the crash. Thank you!

**Comment by djaygit** [comment] 2019-09-26 15:07
1. Okay so i added that in app delegate(right) "#import "MoPub.h"" and couln't run 
<img width="789" alt="Screenshot 2019-09-26 at 8 31 51 PM" src="https://user-images.githubusercontent.com/1255841/65700220-e56a9c00-e09c-11e9-8668-dd7e2604507b.png">
<img width="999" alt="Screenshot 2019-09-26 at 8 31 00 PM" src="https://user-images.githubusercontent.com/1255841/65700221-e56a9c00-e09c-11e9-8f70-c356ca5f06ed.png">
<img width="1034" alt="Screenshot 2019-09-26 at 8 30 53 PM" src="https://user-images.githubusercontent.com/1255841/65700223-e56a9c00-e09c-11e9-8044-08430ecf6ead.png">

2. added in my level1VC #import "MoPub.h"
crashes on MoPub.h line 120

**Comment by chauduyphanvu** [comment] 2019-10-02 17:58
@djaygit, this crash (and perhaps the other one on this thread) is probably caused by the fact that your app is using Manual Reference Counting. Could you follow [our documentation](https://developers.mopub.com/next/ios-integration/#for-apps-using-mrc-tell-the-compiler-to-use-arc) to ensure compatibility with the MoPub iOS SDK? 

Try that and let us know if you continue seeing the crashes. Ensure you keep the MoPub initialization code you added in your previous response. Only make an ad request to MoPub once the SDK has finished initializing via the `completion` handler.

**Comment by djaygit** [comment] 2019-10-05 21:15
> 1. Okay so i added that in app delegate(right) "#import "MoPub.h"" and couln't run
> 
> <img alt="Screenshot 2019-09-26 at 8 31 51 PM" width="789" src="https://user-images.githubusercontent.com/1255841/65700220-e56a9c00-e09c-11e9-8668-dd7e2604507b.png">
> 
> <img alt="Screenshot 2019-09-26 at 8 31 00 PM" width="999" src="https://user-images.githubusercontent.com/1255841/65700221-e56a9c00-e09c-11e9-8f70-c356ca5f06ed.png">
> 
> <img alt="Screenshot 2019-09-26 at 8 30 53 PM" width="1034" src="https://user-images.githubusercontent.com/1255841/65700223-e56a9c00-e09c-11e9-8044-08430ecf6ead.png">
> 
> 1. added in my level1VC #import "MoPub.h"
>    crashes on MoPub.h line 120

ok i tried that and getting this same issue

**Comment by chauduyphanvu** [comment] 2019-10-07 16:58
@djaygit, could you send over your updated project showing the changes you've made? 

To summarize, we want to 1) initialize MoPub, 2) set `Weak References in Manual Retain Release` to `YES`, and 3) add `-fobjc-arc` to all MoPub SDK files in the Build Phases.

**Comment by chauduyphanvu** [comment] 2019-10-14 14:52
@djaygit, there are build errors after you've made the above changes I suggested. Please take action to ensure that the app can successfully build with the changes in place. Once done, feel free to forward your buildable project to _support@mopub.com_ and the team will take a look. We're changing the support path for this issue because we suspect we are dealing with an integration/implementation issue instead of an SDK/adapter issue.

Thank you!

**Closed** 2019-10-14 19:57 UTC
