### ISSUE TITLE
Storekit crashed on ios13 beta5

### ISSUE THREAD

**Issue by red3** [mopub/mopub-ios-sdk#281] opened 2019-08-06 07:40 UTC
when showing storekit, app crashed due to exception: skunsupportedclassexception, reason : SKStoreProductViewController May not be subclassed

#### MoPub SDK Version:
5.8.0 
#### Device model and OS Version:
iPhone Xs Max on iOS 13 beta 5

**Comment by hmertkahraman** [comment] 2019-08-06 10:33
Hi @red3,

Thanks for reaching out to us on this, we'd be happy to guide you through this.

In order for us to identify the problem better, and provide you a comprehensive support, could you please provide some additional details:
- If present, a stack trace log explaining the crash.
- Reproduction steps
- If happened during an ad request lifecycle, the ad unit id, used for requesting the ad.
- Also if present which network adapter is associated with the crash? Can you also please include the version of the network adapter?

Thank you very much in advance,
MoPub Team

**Comment by red3** [comment] 2019-08-07 06:03
@hmertkahraman 

* stack trace 
actually, there was no useful stack trace, Storekit  framework just throw the exception: SKStoreProductViewController May not be subclassed. Seemed like you guys used MPiOS7SafeStoreProductViewController which is a subclass of SKStoreProductViewController.

Not very sure this is Apple's bug or limitation.

**Comment by hmertkahraman** [comment] 2019-08-09 13:19
Hi @red3,

Thanks for letting us know of that. I will investigate this further and get back at you.
Other than this, any information you can provide would be appreciated.

Thanks,
Mert

**Comment by hmertkahraman** [comment] 2019-08-20 16:01
Hi @red3,

After my investigation I'd like to let you know that our SDK team is already aware of the issue and on the works to fix it. 

The problem is caused because Apple doesn't support landscape orientation for SKStoreProductViewController. However due to limitations around how iOS is set up, if an app reports as only supporting landscape (as many games do), the app will crash when attempting to use SKStoreProductViewController.

We originally had a workaround as of iOS7, by subclassing / overriding it such that the VC reports as supporting landscape; but as of iOS 13, subclassing SKStoreProductViewController now also results in a crash. This is why you're getting this error.

Our team is aware of this issue and is preparing a fix, and most likely would be shipped in the upcoming SDKs. You may track the releases for iOS SDK [here](https://github.com/mopub/mopub-ios-sdk/releases). We also do newsletter mailing for such SDK release announcements, you may register [here](https://www.mopub.com/pubupdates) if you haven't done so. 

I hope this helps.

Thanks,
Mert

**Comment by mmdock** [comment] 2019-08-22 22:09
@hmertkahraman 

Interesting fun fact: this is only happening on some ad creatives(all banner ads, but different creatives), but others open just fine.

This is on iOS 13 Beta 8.  Not sure if that makes a difference.

**Comment by Theome** [comment] 2019-09-01 13:00
When will the fix be available? I'm seeing the same crash on my devices running the latest iOS 13 beta, and iOS 13 will be released soon. This is urgent.

**Comment by kogodm** [comment] 2019-09-01 13:46
stack trace here:
2019-09-01 21:35:04.994613+0800 ios[620:88228] Uncaught exception: SKUnsupportedClassException: SKStoreProductViewController may not be subclassed.
(
	0   CoreFoundation                      0x000000019a394b78 CAE91FE5-25A2-3FD0-96CE-EF601CB32324 + 1227640
	1   libobjc.A.dylib                     0x000000019a0bd0a4 objc_exception_throw + 56
	2   CoreFoundation                      0x000000019a28a2a4 CAE91FE5-25A2-3FD0-96CE-EF601CB32324 + 135844
	3   StoreKit                            0x00000001a8b566ec E7CD38E3-F326-3440-984F-A8B6A3F48094 + 128748
	4   ios                                 0x0000000104eea3f4 -[BURewardedVideoAdViewController preloadAppStore] + 832
	5   ios                                 0x0000000104ee8c90 -[BURewardedVideoAdViewController viewDidLoad] + 496
	6   UIKitCore                           0x000000019dd88620 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4048416
	7   UIKitCore                           0x000000019dd8d130 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4067632
	8   UIKitCore                           0x000000019dd8d538 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4068664
	9   UIKitCore                           0x000000019dda2c68 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4156520
	10  UIKitCore                           0x000000019dd9ba78 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4127352
	11  UIKitCore                           0x000000019dd9d3f8 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4133880
	12  UIKitCore                           0x000000019dd9f964 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4143460
	13  UIKitCore                           0x000000019dd9fe60 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4144736
	14  UIKitCore                           0x000000019dd9f8b4 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4143284
	15  UIKitCore                           0x000000019dd9fb1c 16F60E05-42DF-3842-A58E-287B8B9C4DB3 + 4143900
	16  ios                                 0x0000000104f2f70c -[UIViewController(BUUtilities) bu_safelyPresentViewController:animated:completion:] + 120
	17  ios                                 0x0000000104eb5b18 -[BUFullscreenVideoAd showAdFromRootViewController:ritSceneDescribe:] + 732
	18  ios                                 0x0000000104bf9594 -[BUDMopub_InterstitialCustomEvent showInterstitialFromRootViewController:] + 84
	19  ios                                 0x0000000104a91a20 -[MPInterstitialCustomEventAdapter showInterstitialFromViewController:] + 80
	20  ios                                 0x0000000104b4b538 -[MPInterstitialAdManager presentInterstitialFromViewController:] + 308
	21  ios                                 0x0000000104a51e38 -[MPInterstitialAdController showFromViewController:] + 324
	22  ios                                 0x0000000104b49c80 -[MoPubManager showInterstitialAd] + 144
	23  ios                                 0x0000000104c3bf04 _moPubShowInterstitialAd + 152
	24  ios                                 0x0000000106c35960 MoPubiOS_ShowInterstitialAd_mBFFBDDE146D2709497DA1412DDCA77EA56A366A6 + 264
	25  ios                                 0x0000000106424d5c AdPool_Show_m8140671CA2862C926F7828C6F32BBAC04085ABFE + 172
	26  ios                                 0x000000010692da6c InterstitialController_Show_m97824C2A2805DD9F9A6E9767C1A243B983056B70 + 384

**Comment by hmertkahraman** [comment] 2019-09-03 08:57
Hi @mmdock,

Thanks for the input. Yes the issue would happen on some creatives only, when the creative directs user to App Store, which essentially triggers the StoreKit issue for given reasons above. As mentioned [here](https://github.com/mopub/mopub-ios-sdk/issues/281#issuecomment-523081263), we are fully aware of this issue and will be providing a fix soon, most likely in the upcoming SDK releases.

Please let us know if you have any additional questions.

Thanks,
Mert

**Comment by hmertkahraman** [comment] 2019-09-03 08:58
Hi @kogodm,

Thanks for providing details on this. This is already a known issue and a fix is underway. Please refer to [this](https://github.com/mopub/mopub-ios-sdk/issues/281#issuecomment-523081263) answer for details.

Please let us know if you have any additional questions.

Thanks,
Mert

**Comment by hmertkahraman** [comment] 2019-09-03 09:00
Hi @Theome ,

Thanks for reaching out on us. Unfortunately we cannot provide an exact timeline for the fix, but we're estimating it to be available in the next SDK releases. Please actively look out for release notes once the new SDKs are available.

Please let us know if you have any additional questions.

Thanks,
Mert

**Comment by Theome** [comment] 2019-09-03 10:04
@hmertkahraman I'd like to have an update for my app ready as soon as iOS 13 is released to support new iOS 13 features like dark mode. But I cannot send out an update to a million users that crashes the app. 

If the mopub SDK won't be ready soon, I'll have to decide to either provide shiny iOS 13 features or remove mopub ads from my app, so I'd really appreciate an ETA for the next SDK release or a hot fix / workaround for this issue.

**Comment by Theome** [comment] 2019-09-11 08:34
The release of iOS 13 is imminent and Apple now prompts developers to submit their new apps. This issue with the MoPub SDK is holding me back from submitting app updates using new iOS 13 features. The lack of help/communication from MoPub makes me consider this SDK as technical debt in my products.

**Comment by hmertkahraman** [comment] 2019-09-11 08:47
Hi @Theome ,

We will release the fix (mentioned [here](https://github.com/mopub/mopub-ios-sdk/issues/281#issuecomment-523081263)) for this issue by the end of next week, so 20th of September. That would be our SDK version 5.9 release. Please update your MoPub SDK version accordingly.

**cc:** @dive, @aserrr, @aabalaban, @NataliaTs, @jangirtony2009, @mmdock, @kogodm, @red3  

Thanks,
Mert

**Comment by dive** [comment] 2019-09-11 09:07
Hi @hmertkahraman,

Just want to be sure that I read the situation accurately: we have a confirmed reproducible crash within MoPub SDK for applications built with Xcode 11 (aka early adopters of Apple Sign In/new iOS 13 features with planned marketing campaign, agreed on promotions in the AppStore, etc.), and you are going to release an update with the fix one day after iOS 13 release, right?

Thanks,
Artem

**Comment by samwize** [comment] 2019-09-14 13:39
I am surprise a hotfix is not released, when Xcode GM is now ready, and iOS 13 will be officially release on Sep 19. Just 5 more days. 

I have to disable MoPub interstitial ads for my app update. 

To be fair, I think Admob uses the same technique, and have to release a fix yet. Who will be faster? :(

**Comment by chauduyphanvu** [comment] 2019-09-14 13:46
Hi everyone, to clarify, we should have a release BEFORE September 20. We're targeting early next week for that, so you can perform any necessary upgrade before iOS 13 is released on September 19.

Vu Chau
MoPub SDK Team

**Comment by chauduyphanvu** [comment] 2019-09-16 20:58
The 5.9.0 iOS SDK is now live that should contain the fix. Please upgrade and let us know if you continue seeing the crash!

**Closed** 2019-09-20 21:47 UTC
