### ISSUE TITLE
stuck when playing rewarded videos on iOS 13 and iPhone X devices

### ISSUE THREAD

**Issue by LongJiangSB** [mopub/mopub-ios-sdk#357] opened 2020-12-03 06:12 UTC
One line summary of the issue here

- [√] I am submitting a bug report for existing functionality
- [√] I visited https://developers.mopub.com/ and found no answer
- [√] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [√] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15.0
#### Device model and OS Version:
iPhone X, iOS 13.0
#### Xcode Version:
12.0
#### Ad Unit IDs used in reproducing the issue:
NO
#### Steps to reproduce the behavior:
I found that there is still a situation of stuck when playing rewarded videos on iOS 13 and iPhone X devices. The close, get, and advertising buttons on the page can be clicked normally.

Later I use the official test video ID: `8f000bd5e00246de9c789eed39ff6096` I tested it on the same iOS13 device, and the result was that the video was stuck and the countdown was working normally. After the countdown, the top became a skip button, click to close.

this is my podfile
```
source "https://github.com/CocoaPods/Specs.git"
install! 'cocoapods', :deterministic_uuids => false
platform :ios, '10.0'

target 'AdMopubSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'mopub-ios-sdk/Core' , '~>5.15.0'

end
```

#### Expected behavior:
Displaying Video Ad successfully

#### Observed behavior:
No

#### Evidence:
No

TestProject
[mopubTest.zip](https://github.com/mopub/mopub-ios-sdk/files/5635640/mopubTest.zip)

**Comment by LongJiangSB** [comment] 2020-12-03 07:26
When I don’t delete the swift file, the program runs normally, but I found that there is still a situation of stuck when playing rewarded videos on iOS 13 and iPhone X devices. The close, get, and advertising buttons on the page can be clicked normally.

**Comment by chauduyphanvu** [comment] 2020-12-03 17:55
@LongJiangSB, your zipped app doesn't do anything on launch. I'm seeing a black screen:

```
2020-12-03 12:54:17.494397-0500 mopubTest[35997:16300455] [Application] The app delegate must implement the window property if it wants to use a main storyboard file.
```

Are you able to share a screen recording of the behavior you are seeing? Thanks!

Vu Chau
MoPub Team

**Comment by LongJiangSB** [comment] 2020-12-04 02:16
[mopubTest+video.zip](https://github.com/mopub/mopub-ios-sdk/files/5640154/mopubTest%2Bvideo.zip)
this is new demo + screen recording, thanks for your reply.

**Comment by LongJiangSB** [comment] 2020-12-04 03:01
> @LongJiangSB, your zipped app doesn't do anything on launch. I'm seeing a black screen:
> 
> ```
> 2020-12-03 12:54:17.494397-0500 mopubTest[35997:16300455] [Application] The app delegate must implement the window property if it wants to use a main storyboard file.
> ```
> 
> Are you able to share a screen recording of the behavior you are seeing? Thanks!
> 
> Vu Chau
> MoPub Team

this is new demo + screen recording, thanks for your reply.
[mopubTest+video.zip](https://github.com/mopub/mopub-ios-sdk/files/5640336/mopubTest%2Bvideo.zip)

**Comment by LongJiangSB** [comment] 2020-12-14 05:04
@chauduyphanvu Hello, is there any successor to my question? Thank you！

**Comment by chauduyphanvu** [comment] 2020-12-23 21:36
@LongJiangSB, thank you for the information. I haven't been able to reproduce this issue on my devices yet, but when I am I will update this thread.

Does this issue occur on any other devices?

**Comment by chauduyphanvu** [comment] 2021-01-21 22:31
Closing since the issue cannot be reproduced.

**Closed by chauduyphanvu** 2021-01-21 22:31 UTC
