### ISSUE TITLE
Calling MPInterstitialAdController gives "argument passed to call that takes no arguments" sometimes

### ISSUE THREAD

**Issue by DavidLu7973** [mopub/mopub-ios-sdk#304] opened 2019-11-12 21:25 UTC
I sometimes get a build error when I'm building my app with MoPub ads.

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.10.0
#### Xcode Version:
11.1
#### Ad Unit IDs used in reproducing the issue:
4f117153f5c24fa6a3a92b818a5eb630

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

`    var interstitial: MPInterstitialAdController =
    MPInterstitialAdController(forAdUnitId: "4f117153f5c24fa6a3a92b818a5eb630")`

#### Expected behavior:
I expect to load an ad and have my code build successfully.

#### Observed behavior:
When I try returning an interstitial ad object for the ad unit ID

`MPInterstitialAdController(forAdUnitId: "4f117153f5c24fa6a3a92b818a5eb630")` 

gives me an error. This error only happens on occasion, I'm still able to build and run ads ~50% of the time.

![Screen Shot 2019-11-12 at 1 24 10 PM](https://user-images.githubusercontent.com/7572886/68712061-c7270580-054f-11ea-8500-8975c546a108.png)

If I force and try to rebuild the app several times, the build will eventually succeed and ads appear in my app. The behavior is inconsistent and it's unclear why this error appears intermittently.

**Comment by dravyan** [comment] 2019-11-12 23:03
@DavidLu7973 , thanks for reporting. This looks to me like the Swift compiler version you are using. Can you share the Xcode and the Swift version you are on? Can you try with the recent versions? Let me know how it goes.

Thanks,
Dravya Nataraj
MoPub Team

**Comment by DavidLu7973** [comment] 2019-11-13 21:46
@dravyan I have my Swift compiler version set to Swift 5, and my Xcode version is 11.1. I updated to Xcode 11.2.1 and am still seeing the same error.

![Screen Shot 2019-11-13 at 12 45 49 PM](https://user-images.githubusercontent.com/7572886/68802841-8bee0a80-0613-11ea-9d77-e02d60f5d061.png)

**Comment by dravyan** [comment] 2019-11-15 16:13
@DavidLu7973, we have not been able to replicate the issue on our end. Can you share a sample project where we can see this issue to investigate further?

Thanks,
Dravya Nataraj
MoPub Team

**Comment by rsatrasala** [comment] 2019-12-20 23:37
Closing due to lack of reproduction steps. Please reopen a new issue if needed

**Closed by rsatrasala** 2019-12-20 23:37 UTC

**Comment by victorcampeanu** [comment] 2021-01-06 11:22
same with Xcode Version 12.3 (12C33) and Swift f
